### ISSUE TITLE
Error validation subscription keys: Undefined property: stdClass::$licenses

### ISSUE THREAD

**Issue by spetters** [slunak/pushover-php#13]
We're using Pushover and this great wrapper for our application to notify users about upcoming events. For easy handling we're using the Pushover Subscription API, so instead of user keys, we have subscription keys. Other as stated in the Pushover documentation, the response seems to not contain the licenses for the user. This leads to an error:

Undefined property: stdClass::$licenses
in serhiy/pushover/src/Client/Response/UserGroupValidationResponse.php in line 103

Steps to reproduce:

1.) Acquire subscription key via Pushover Subscription API
2.) Try to validate using Serhiy\Pushover\Api\UserGroupValidation\Validation

$application = new Application($appId);
$validation = new Validation($application);
$recipient = new Recipient($subscriptionKey);

$response = $validation->validate($recipient);

The last line throws this message

Potential fix:

Check if response contains licenses data prior to accessing it. Since PHP 7 it is possible to use null-coalesence operator ??.
Replace line 103 as follows:

$this->setLicenses($decodedCurlResponse->licenses ?? []);

Thank you for your great work!

Best regards,
Sebastian

**Comment by slunak** [comment]
Thanks for reporting the issue, @spetters. Let me look into it during the next few days and come back with a fix.

**Comment by spetters** [comment]
We are using a subscription key. As far as we understand the API documentation, user keys, group keys and also subscription keys are handled the same. So let's say, our hope was, the subscription keys can also be verified. Besides not returning information about licences, the status seems to be correct:

`{
    "devices": [
        "device 1",
        "device 2"
    ],
    "group": 0,
    "request": "reducted",
    "status": 1
}`

I can create an app and subscription keys for testing if this helps.

**Comment by slunak** [comment]
According to API documentation (https://pushover.net/api#validate), only "the user's or group's identifier" can be validated. It does not mention subscription keys in validation section.

I played a bit more with subscriptions and it seems like I can reproduce the issue. Users, when subscribed to an Application, are added to a Delivery Group. Each user in the group gets newly generated User Key. Keys can be found under Group Members. Validating such key indeed produces a response without licenses array.

In my opinion, the array should be there and this may be an issue on Pushover side. I can produce a workaround for now, but I will contact Joshua from Pushover and ask why licenses array is not included in the response.

How urgently do you need a fix?

**Comment by spetters** [comment]
Thank you very much!

Since only validation is affected we can skip this in our development environment as a workaround, so this is not an urgent topic for now. It would be great to find a correct solution.

From the Pushover API docs it was not really clear if user keys and subscription keys are interchangeable everywhere. Also the Message API does not mention them. Maybe Joshua can clarify.

**Comment by slunak** [comment]
I have submitted a support case. Let's also ask @jcs here politely :)

**Comment by jcs** [comment]
Hi, the Pushover user validation API now returns a blank `licenses` array for subscribed user keys.

**Comment by spetters** [comment]
Thank you @jcs ! I can confirm, validation now works as expected. This issue is resolved.
