### ISSUE TITLE
Travis CI PHP 8.2 version workaround

### ISSUE THREAD

**Issue by slunak** [slunak/pushover-php#18]
Travis is missing a library when building PHP 8.2 environment. At the moment I implemented a workaround I described here:

https://travis-ci.community/t/php-8-2-support/13401

I would need to come back to this later when Travis properly supports 8.2.

**Comment by slunak** [comment]
@OskarStark just wondering if you have time to look into GitHub actions instead of using Travis? Otherwise I can look into implementing it no problem.

**Comment by OskarStark** [comment]
Sure I will check it next week after my vacation 🤓

**Comment by slunak** [comment]
All right, sorry for bothering :)

**Comment by OskarStark** [comment]
No, thanks for the reminder 😝
