### ISSUE TITLE
Implement Creating a Group 

### ISSUE THREAD

**Issue by Vitexus** [slunak/pushover-php#26]
https://pushover.net/api/groups#create

**Comment by slunak** [comment]
Are you planning to work on this @Vitexus ?

**Comment by Vitexus** [comment]
Thanks for fast reaction.

Now I'm try to hack in somehow :) 

```php
        $group = new Group(str_repeat('0', 30), $this->application);
```


It give me background for further pull request.

**Comment by Vitexus** [comment]
Its almost clean :smile: 
![image](https://github.com/user-attachments/assets/a489e56e-8593-4025-a4ce-a43851475a5d)
